//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HocamNerede
{
    using System;
    using System.Collections.Generic;
    
    public partial class poolOkulFakulte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public poolOkulFakulte()
        {
            this.poolFakulteBolum = new HashSet<poolFakulteBolum>();
        }
    
        public int Id { get; set; }
        public int FFakulteID { get; set; }
        public int FOkulID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<poolFakulteBolum> poolFakulteBolum { get; set; }
        public virtual tblFakulteler tblFakulteler { get; set; }
        public virtual tblOkullar tblOkullar { get; set; }
    }
}
