//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HocamNerede
{
    using System;
    using System.Collections.Generic;
    
    public partial class poolFakulteBolum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public poolFakulteBolum()
        {
            this.poolBolumDers = new HashSet<poolBolumDers>();
        }
    
        public int Id { get; set; }
        public int FpoolokulfalulteID { get; set; }
        public int FBolumID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<poolBolumDers> poolBolumDers { get; set; }
        public virtual poolOkulFakulte poolOkulFakulte { get; set; }
        public virtual tblBolumler tblBolumler { get; set; }
    }
}
