//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HocamNerede
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHvz
    {
        public int ID { get; set; }
        public int FGunID { get; set; }
        public System.TimeSpan BaslangicSaati { get; set; }
        public Nullable<int> FpoolBolumdersID { get; set; }
        public System.TimeSpan BitisSaati { get; set; }
    
        public virtual poolBolumDers poolBolumDers { get; set; }
        public virtual tblGunler tblGunler { get; set; }
    }
}
