//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HocamNerede
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOkullar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOkullar()
        {
            this.poolOkulFakulte = new HashSet<poolOkulFakulte>();
        }
    
        public int Id { get; set; }
        public string OkulName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<poolOkulFakulte> poolOkulFakulte { get; set; }
    }
}
